package com.supplychain.ai.controller;

import com.supplychain.ai.dto.ChatRequest;
import com.supplychain.ai.dto.ConversationDTO;
import com.supplychain.ai.dto.MessageDTO;
import com.supplychain.ai.service.AiService;
import com.supplychain.common.response.ApiResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.*;
import reactor.core.publisher.Flux;

import java.util.List;
import java.util.Map;

/**
 * REST Controller for AI chat, insights, and forecasting endpoints.
 * Supports Server-Sent Events streaming for real-time AI responses.
 */
@RestController
@RequestMapping("/ai")
@RequiredArgsConstructor
@Slf4j
@Tag(name = "AI Intelligence", description = "AI chat assistant, insights, and forecasting APIs")
@SecurityRequirement(name = "bearerAuth")
public class AiController {

    private final AiService aiService;

    /**
     * Streams AI chat response using Server-Sent Events.
     * Supports multi-agent routing based on message content.
     */
    @PostMapping(value = "/chat", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    @Operation(summary = "Stream AI chat response",
               description = "Sends message to AI and streams response using SSE")
    public Flux<String> chat(
            @Valid @RequestBody ChatRequest request,
            @AuthenticationPrincipal UserDetails userDetails) {
        log.debug("AI chat request from user: {}", userDetails.getUsername());
        return aiService.processChat(userDetails.getUsername(), request)
                .map(content -> "data: " + content + "\n\n")
                .concatWith(Flux.just("data: [DONE]\n\n"));
    }

    /**
     * Gets business insights generated by AI agents.
     */
    @GetMapping("/insights")
    @Operation(summary = "Get AI business insights",
               description = "Returns AI-generated business insights and recommendations")
    public ResponseEntity<ApiResponse<List<Map<String, Object>>>> getInsights() {
        List<Map<String, Object>> insights = aiService.getBusinessInsights();
        return ResponseEntity.ok(ApiResponse.success(insights, "AI insights retrieved successfully"));
    }

    /**
     * Gets demand forecast for a specific product.
     */
    @GetMapping("/forecast/{productId}")
    @Operation(summary = "Get AI demand forecast",
               description = "Returns AI-powered demand forecast for a product")
    public ResponseEntity<ApiResponse<Map<String, Object>>> forecastDemand(
            @PathVariable Long productId,
            @RequestParam(defaultValue = "30") int days) {
        Map<String, Object> forecast = aiService.forecastDemand(productId, days);
        return ResponseEntity.ok(ApiResponse.success(forecast, "Demand forecast generated successfully"));
    }

    /**
     * Gets AI conversation history for the authenticated user.
     */
    @GetMapping("/conversations")
    @Operation(summary = "Get conversation history",
               description = "Returns list of AI conversations for the current user")
    public ResponseEntity<ApiResponse<List<ConversationDTO>>> getConversations(
            @AuthenticationPrincipal UserDetails userDetails) {
        List<ConversationDTO> conversations = aiService.getConversations(userDetails.getUsername());
        return ResponseEntity.ok(ApiResponse.success(conversations, "Conversations retrieved successfully"));
    }

    /**
     * Gets messages for a specific conversation.
     */
    @GetMapping("/conversations/{conversationId}/messages")
    @Operation(summary = "Get conversation messages",
               description = "Returns all messages in a specific AI conversation")
    public ResponseEntity<ApiResponse<List<MessageDTO>>> getConversationMessages(
            @PathVariable Long conversationId,
            @AuthenticationPrincipal UserDetails userDetails) {
        List<MessageDTO> messages = aiService.getConversationMessages(
                conversationId, userDetails.getUsername());
        return ResponseEntity.ok(ApiResponse.success(messages, "Messages retrieved successfully"));
    }
}
